# 1. https://github.com/ampache/ampache-docker
---
#version: "3.3"

networks:
  traefik-proxy:
    driver: overlay
    attachable: true
    external: true

volumes:
  # shared mountpoint via NFS
  #
  # FIXME(JEFF): I cannot convince Docker to use NFSv4 -- it
  # I would love to find an answer for this!
  #
  # FIXME(JEFF): We cannot use this volume until we figure
  # out how to tell Docker to continue running the container
  # even if the connection here errors out. I believe that
  # we ought to consider looking at other options, such
  # as rclone.
  music:
    driver: local
    driver_opts:
      type: nfs
      o: addr=fs1-san.home,nolock,soft,rw,vers=4
      device: :/mnt/npool0/smb/Music
  # mpd
  mpd_database:
    external: false
  # ampache
  mysql_db:
    external: false

services:
  mpd:
    restart: always
    image: "giof71/mpd-alsa:latest"
    container_name: "mpd-1"
    # ALSA
    devices:
      - /dev/snd
    ports:
      - "6600:6600"
    env_file:
      - .env
    volumes:
      # bind mounts
      - /etc/localtime:/etc/localtime:ro
      - ./mounts/logs/mpd:/log:rw
      - ./mounts/config/mpd:/user/config:rw
      # volumes
      - mpd_database:/db:rw
      # playlists are at /music/playlists
      - /mnt/fs1/Music:/music:rw
      #- music:/music:rw
    networks:
      - traefik-proxy
    cpus: 0.5
    mem_limit: 512M
    labels:
      - "traefik.enable=false"
      - "homepage.group=syn"
      - "homepage.name=mpd"

  ampache:
    depends_on:
      - mpd
    restart: unless-stopped
    image: ampache/ampache:6.3.1
    container_name: "ampache-1"
    ports:
      - "9700:80/tcp"
    volumes:
      # bind mounts
      - /etc/localtime:/etc/localtime:ro
      - ./mounts/logs/ampache:/var/log/ampache:rw
      - ./mounts/config/ampache:/var/www/config:rw
      # volume mounts
      - mysql_db:/var/lib/mysql:rw
      # playlists are at /media/playlists
      - /mnt/fs1/Music:/media:ro
      #- music:/media:nocopy,ro 
    env_file:
      - .env
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ampache.rule=Host(`music.fs1.home`) && PathPrefix(`/`)"
      - "traefik.http.routers.ampache.entrypoints=websecure"
      - "traefik.http.services.ampache.loadbalancer.server.port=80"
      - "traefik.http.routers.ampache.service=ampache"
      - "traefik.http.routers.ampache.tls.certresolver=staging-web-acme"
      - "homepage.group=syn"
      - "homepage.name=ampache"
      - "homepage.href=https://music.fs1.home"
    cpus: 0.5
    mem_limit: 256M
